const studentInfo = [
  {
    stu_id: "546468",
    name: "farid",
    email: "faahsan1516@gmail.com",
    section: "A",
    class: "two",
  },
  {
    stu_id: "544468",
    name: "shakil",
    email: "faahsan1516@gmail.com",
    section: "A",
    class: "two",
  },
  {
    stu_id: "546468",
    name: "nirupom",
    email: "faahsan1516@gmail.com",
    section: "A",
    class: "two",
  },
  {
    stu_id: "5358468",
    name: "tareq",
    email: "faahsan1516@gmail.com",
    section: "A",
    class: "two",
  },
  {
    stu_id: "846468",
    name: "sabbir",
    email: "faahsan1516@gmail.com",
    section: "A",
    class: "two",
  },
  {
    stu_id: "546328",
    name: "zihad",
    email: "faahsan1516@gmail.com",
    section: "A",
    class: "two",
  },
  {
    stu_id: "325641",
    name: "shagor",
    email: "faahsan1516@gmail.com",
    section: "A",
    class: "two",
  },
  {
    stu_id: "652348",
    name: "rakib",
    email: "faahsan1516@gmail.com",
    section: "A",
    class: "two",
  },
  {
    stu_id: "5658468",
    name: "foysol",
    email: "faahsan1516@gmail.com",
    section: "A",
    class: "two",
  },
  {
    stu_id: "874468",
    name: "sayem",
    email: "faahsan1516@gmail.com",
    section: "A",
    class: "two",
  },
];
